### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by cands** [stephancasas/alfred-mouseless-messenger#1]
This seems very useful, unfortunately it does not work for me on macOS 12.4 and Alfred 4.6.6 [1303]. Full Disk Access has been granted and Alfred has been restarted (also restarted the computer just in case). The debugger provides the following brief information: 
 
`ERROR: Mouseless Messenger[Script Filter] Code 1: /Users/***/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/A1EB22C3-A50D-427E-B2D8-2632031A2F76: execution error: Error: Error: Can't get object. (-1728)`

**Comment by stephancasas** [comment]
Please try installing again using this new release: https://github.com/stephancasas/alfred-mouseless-messenger/releases/tag/v1.0.1

**Comment by cands** [comment]
Thank you, I confirm that this resolved the issue!
